version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: mc.web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - minecraft

  router:
    image: itzg/mc-router
    container_name: mc.router
    ports:
      - 25565:25565
    links:
      - minecraft
    command: --mapping=0.0.0.0=minecraft:25565

  minecraft:
    image: itzg/minecraft-server:java17
    container_name: mc.server
    environment:
      EULA: "true"
      TYPE: "PAPER"
      VERSION: "1.19.1"
      MOTD: ""
      RCON_PASSWORD: ""
      SLACK_BOT_TOKEN: ""
      SLACK_SIGNING_SECRET: ""
      UID: 1000
      GID: 1000
    ports:
      - 25565
      - 8123 
      - 3000
    volumes:
      - ./data:/data
